---

# Tests whether two environment variables are present (and non-empty)

- hosts: local
  connection: local
  tasks:
    - shell: 'test -n "${AZURE_SUBSCRIPTION_ID}"'
    - shell: 'test -n "${AZURE_CERT_PATH}"'
