---

- hosts: all
  gather_facts: false
  tasks:
    - debug: var=var1
      when: var1 is defined

    - debug: msg='var1 not defined'
      when: var1 is not defined

    - debug: var=var2
      when: var1 is defined

    - debug: msg='var2 not defined'
      when: var2 is not defined
