---
- name: add hosts to inventory
  hosts: all
  vars:
    num_hosts: 10
  tasks:
    - name: create inventory
      add_host:
        name: 'host-{{item}}'
        groups: dynamic
        ansible_connection: local
        host_id: '{{item}}'
      with_sequence: start=1 end={{num_hosts}} format=%d
      notify:
          - single host handler

  handlers:
    - name: single host handler
      command: 'true'


- name: various task responses on dynamic inventory
  hosts: 'dynamic'
  tasks:
    - name: fail even numbered hosts
      command: 'false'
      when: host_id|int % 2 == 0
    - name: skip multiples of 3
      command: 'true'
      when: host_id|int % 3 != 0
    - name: all skipped
      command: 'true'
      when: false
    - name: all changed
      command: 'true'
      notify:
          - changed handler
    - name: all ok
      command: 'true'
      changed_when: false
      notify:
          # this will never notify since the task never is changed: true
          - ok handler
  handlers:
    - name: ok handler
      command: 'false'
    - name: changed handler
      command: 'true'
      notify: another changed handler
    - name: yet another changed handler
      command: 'true'
    - name: another changed handler
      command: 'true'


- name: shrink inventory to 1 host
  hosts: 'dynamic'
  tasks:
    - name: fail all but 1
      command: 'false'
      when: host_id|int != 1


- name: 1 host play
  hosts: 'host-1'
  gather_facts: false
  tasks:
    - name: pass
      command: 'true'
    - name: ok
      command: 'true'
      changed_when: false
    - name: ignored
      command: 'false'
      ignore_errors: true


- name: fail remaining dynamic group
  hosts: all
  gather_facts: true
  tasks:
    - name: fail
      command: 'false'
      when: inventory_hostname == 'host-1'


- name: add hosts to inventory
  hosts: all
  vars:
    num_hosts: 10
  tasks:
    - name: add dynamic inventory
      add_host:
        name: 'new-host-{{item}}'
        groups: dynamic
        ansible_connection: local
        host_id: '{{item}}'
      with_sequence: start=1 end={{(num_hosts|int / 2)|int}} format=%d
    - name: add unreachable inventory
      add_host:
        name: 'unreachable-host-{{item}}'
        groups: unreachable
        ansible_connection: ssh
        host_id: '{{item}}'
      with_sequence: start={{(num_hosts|int / 2)|int + 1}} end={{num_hosts}} format=%d
    - name: add more_unreachable inventory
      add_host:
        name: 'more-unreachable-host-{{item}}'
        groups: more-unreachable
        ansible_connection: ssh
        host_id: '{{item}}'
      with_sequence: start={{(num_hosts|int / 2)|int + 1}} end={{num_hosts}} format=%d


- name: some unreachable, some changed, some skipped
  hosts: 'dynamic:unreachable'
  gather_facts: false
  tasks:
    - name: all changed with items
      command: 'true'
      when: host_id|int % 5 == 0


- name: no matching hosts
  hosts: no_hosts_will_ever_match_this_string


- name: gather facts fail
  hosts: unreachable
  gather_facts: true


- name: some gather facts fail
  hosts: more-unreachable:dynamic
  gather_facts: true
  tasks:
    - name: skip this task
      command: 'false'
      when: false


- name: no tasks, just the facts
  hosts: all
