---

- hosts: all
  gather_facts: false
  strategy: free
  tasks:
    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='1: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='2: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='3: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='4: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='5: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='6: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='7: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='8: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='9: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - action: wait_for timeout={{ 5|random }}
      register: waited
    - debug: "msg='10: {{ waited.elapsed }} seconds'"
    - set_fact: wait_counter={{ waited.elapsed|int + wait_counter|int }}

    - debug: msg="{{ inventory_hostname }} waited for {{ wait_counter }} seconds."
