---

# Tests whether two environment variables are present (and non-empty)

- hosts: local
  connection: local
  tasks:
    - shell: 'test -n "${GCE_EMAIL}"'
    - shell: 'test -n "${GCE_PROJECT}"'
    - shell: 'test -n "${GCE_PEM_FILE_PATH}"'
