--- 
- 
  hosts: all
  gather_facts: true
  become: true
  tasks:

- 
      name: "7. Uninstall HTTPD/Apache"
      tags: uninstall_apache
      yum:
        name: httpd
        autoremove: yes
        state: absent
