--- 
- 
  become_user: root
  gather_facts: true
  hosts: all
  tasks: 
    - 
      name: check os release
    - 
      debug: 
        msg: 
          - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
          - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
          - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
  vars: 
    ansible_python_interpreter: "/usr/bin/env python3"
