- hosts: all
  gather_facts: false
  tasks:
    - test_scan_facts:
    - debug:
        msg: "{{item}}"
      with_items:
         - "{{string}}"
         - "{{unicode_string}}"
         - "{{int}}"
         - "{{float}}"
         - "{{bool}}"
         - "{{null}}"
         - "{{list}}"
         - "{{obj}}"
         - "{{empty_list}}"
         - "{{empty_obj}}"
