---
#
# Sample playbook designed to execute various tasks without spawning a python process
#
- hosts: all
  gather_facts: False
  tasks:
    - set_fact: x=0
    - set_fact: x=1
    - set_fact: x=2
    - set_fact: x=3
    - set_fact: x=4
    - set_fact: x=5
    - set_fact: x=6
    - set_fact: x=7
    - set_fact: x=8
    - set_fact: x=9
    - set_fact: x=10
    - set_fact: x=11
    - set_fact: x=12
    - set_fact: x=13
    - set_fact: x=14
    - set_fact: x=15
    - set_fact: x=16
    - set_fact: x=17
    - set_fact: x=18
    - set_fact: x=19
    - set_fact: x=20
    - set_fact: x=21
    - set_fact: x=22
    - set_fact: x=23
    - set_fact: x=24
    - set_fact: x=25
    - set_fact: x=26
    - set_fact: x=27
    - set_fact: x=28
    - set_fact: x=29
    - set_fact: x=30
    - set_fact: x=31
    - set_fact: x=32
    - set_fact: x=33
    - set_fact: x=34
    - set_fact: x=35
    - set_fact: x=36
    - set_fact: x=37
    - set_fact: x=38
    - set_fact: x=39
    - set_fact: x=40
    - set_fact: x=41
    - set_fact: x=42
    - set_fact: x=43
    - set_fact: x=44
    - set_fact: x=45
    - set_fact: x=46
    - set_fact: x=47
    - set_fact: x=48
    - set_fact: x=49
