---
- name: test_task_tags
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: task_with_tag
      debug: msg=
      tags: tag
    - name: task_with_multiple_tags
      debug: msg=
      tags: [tag, other_tag]
    - name: task_with_always_tag
      debug: msg=
      tags: always
    - name: task_without_tag
      debug: msg=

- name: test_inherited_tags
  hosts: localhost
  gather_facts: False
  connection: local
  tags:
    - inherited_tag
  tasks:
    - name: task_with_inherited_tag
      debug: msg=

- name: test_role_tags
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
    - { role: test_tag_role, test_tag_role_msg: 'role_with_tag', tags: [ 'tag_role' ] }

- include: test_tags_include.yml
  tags: tag_include
