---
- hosts: localhost
  gather_facts: false
  vars:
    collection_id: awx.awx
  tasks:
    - name: "Create playbook to call with collection FQCN"
      template:
        src: tower_collection_smoke.j2
        dest: tower_collection_actual.yml

    - include: tower_collection_actual.yml

    - name: "Delete dynamic playbook"
      file:
        path: tower_collection_actual.yml
        state: absent
